### PR TITLE
Hdf5

### LINKED ISSUE #3: Spectra in HDF5 format
Someone has to do it. I suggest a folder utils with some scripts that do things like rewrite the database in new format, produce hdf spectra etc.

### PR DESCRIPTION
**Pull request by kcotar**
Combined spectra in the HDF5 format are currently written to a file reductions/results/190231/spectra/190231_com.hdf5

Close #3

### CODE REVIEW

**Comment by sheliak** [comment]
I see you added feh in addition to met value in the database. Is there a good reason for both? You also have to add a description around line 3727 and add the same parameter into headers of individual fits files, not jus tthe database.

**Comment by sheliak** [comment]
hdf5 serialisation should be a standalone script in folder utils.

**Comment by kcotar** [comment]
@sheliak It is easier to comment the code using code review functionality.

> I see you added feh in addition to met value in the database. Is there a good reason for both? You also have to add a description around line 3727 and add the same parameter into headers of individual fits files, not jus tthe database.

You already did that by appending both, met and feh Columns to the final output Table. As the number of Columns and parameters was not he same in the add_row function, I added feh that was missing.

As for the HDF5, we can transform it to a utility tool.

**Comment by kcotar** [comment]
Close #18 

Source https://github.com/tensorflow/tensorflow/issues/27023

**Pull request merged**
